name: Daily TTC Scraper

on:
  schedule:
    # Run every day at 11:00 PM UTC (adjust timezone as needed)
    - cron: '0 23 * * *'
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install selenium webdriver-manager
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        
    - name: Run scraper
      run: python scraper.py
      
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add data/ttc_passengers.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update TTC data - $(date +'%Y-%m-%d')" && git push)